package simulation.event;

import simulation.network.entity.Node;
import simulation.network.entity.Payload;

import java.util.List;

/**
 * Initialization event for triggering the start of a simulation.
 *
 * @param <T> Message class carried by payloads generated by the type of protocol being simulated.
 */
public class InitializationEvent<T> extends NodeEvent<T> {

    public static final double START_TIME = 0;

    /**
     * @param node Node to be initialized.
     */
    public InitializationEvent(Node<T> node) {
        super(START_TIME, node);
    }

    @Override
    public List<NodeEvent<T>> simulate() {
        List<Payload<T>> payloads = getNode().initializationPayloads();
        return EventUtil.convertPayloadsToQueueEvents(START_TIME, getNode(), payloads);
    }

    @Override
    public String toString() {
        return super.toString() + " (Initialization): " + getNode();
    }
}
