package simulation.event;

import simulation.network.entity.Node;
import simulation.network.entity.Payload;

import java.util.List;

/**
 * Polls the message queue from the given {@code Node}.
 *
 * The event checks to see if the {@code node} is not currently occupied and has messages in its queue
 * before polling from the message queue to be processed.
 *
 * @param <T> Message class carried by payloads generated by the type of protocol being simulated.
 */
public class PollQueueEvent<T> extends NodeEvent<T> {

    private Payload<T> payload;

    public PollQueueEvent(double time, Node<T> node) {
        super(time, node);
    }

    @Override
    public List<NodeEvent<T>> simulate() {
        Node<T> node = getNode();
        if (!node.isEmpty() && !node.isOccupiedAtTime(getTime())) {
            payload = node.popFromQueue();
            return List.of(new ProcessPayloadEvent<>(getTime(), node, payload));
        } else {
            return List.of();
        }
    }

    @Override
    public String toString() {
        return super.toString() + " (PollQueueEvent): Polling from " + getNode() + " (" + payload + ")";
    }
}
