package simulation.event;

import simulation.network.entity.BFTMessage;
import simulation.network.entity.Validator;

import java.util.List;

/**
 * Represents a timed notification event for the given {@code node}.
 *
 * This class is mostly used for nodes to implement timeout mechanisms.
 *
 * @param <T> Message class carried by payloads generated by the type of protocol being simulated.
 */
public class TimedEvent<T extends BFTMessage> extends NodeEvent<T> {

    private final Validator<T> node;
    private final int id;
    private final int timerCount;

    public TimedEvent(double time, Validator<T> node, int id, int timerCount) {
        super(time, node);
        this.node = node;
        this.id = id;
        this.timerCount = timerCount;
    }

    @Override
    public List<NodeEvent<T>> simulate() {
        return List.of(new QueueEvent<>(getTime(), node, node.notifyTime(id, timerCount)));
    }

    @Override
    public String toString() {
        return super.toString() + " (Timed): Notifying " + node + " at " + getTime();
    }
}
