package simulation.network.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Represents an endpoint node in a network that sends and receives messages via the network.
 *
 * @param <T> Message class generated by {@code EndpointNode}.
 */
public abstract class EndpointNode<T> extends Node<T> {

    /**
     * Nodes (usually switches) directly connected to {@code this} for message sending.
     */
    private List<Node<T>> outflowNodes;

    /**
     * @param name Name of node.
     */
    public EndpointNode(String name) {
        super(name);
        this.outflowNodes = new ArrayList<>();
    }

    public void setOutflowNodes(List<Node<T>> outflowNodes) {
        this.outflowNodes = new ArrayList<>(outflowNodes);
    }

    public List<Node<T>> getOutflowNodes() {
        return outflowNodes;
    }

    /**
     * Randomly returns one of the switches that leads to the network.
     */
    @Override
    public Node<T> getNextNodeFor(Payload<T> payload) {
        if (outflowNodes.size() == 0) {
            throw new RuntimeException(String.format("Outflow neighbors not initialized for %s", this));
        }
        // random tiebreaker
        int randomIndex = new Random().nextInt(outflowNodes.size());
        return outflowNodes.get(randomIndex);
    }
}
