package simulation.network.entity;

import simulation.network.entity.timer.TimerNotifier;
import simulation.simulator.ValidatorResults;
import simulation.statistics.ConsensusStatistics;
import simulation.util.Pair;
import simulation.util.rng.RandomNumberGenerator;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Encapsulates an {@code EndpointNode} that runs a BFT protocol.
 *
 * @param <T> Message class generated by {@code Validator}.
 */
public abstract class Validator<T extends BFTMessage> extends TimedNode<T>
        implements ValidatorResults {

    private final int id;
    private final Map<Integer, Validator<T>> allNodes;
    private final ConsensusStatistics statistics;
    private final int consensusLimit;

    /**
     * @param name Name of validator.
     * @param id Unique integer identifier for validator.
     * @param consensusLimit Consensus count limit.
     * @param timerNotifier TimerNotifier to check time and set timers.
     * @param serviceTimeGenerator RNG for service time.
     * @param states States for the BFT protocol. Used for tracking statistics.
     */
    public Validator(String name, int id, int consensusLimit, TimerNotifier<T> timerNotifier,
            RandomNumberGenerator serviceTimeGenerator, Collection<Object> states) {
        super(name, timerNotifier, serviceTimeGenerator);
        this.allNodes = new HashMap<>();
        this.id = id;
        this.statistics = new ConsensusStatistics(states);
        this.consensusLimit = consensusLimit;
    }

    public void setAllNodes(List<? extends Validator<T>> allNodes) {
        for (Validator<T> node : allNodes) {
            this.allNodes.put(node.getId(), node);
        }
    }

    public Collection<Validator<T>> getAllNodes() {
        return allNodes.values();
    }

    public Validator<T> getNode(int id) {
        return allNodes.get(id);
    }

    protected void broadcastMessageToAll(T message) {
        broadcastMessage(message, getAllNodes());
    }

    public int getId() {
        return id;
    }

    @Override
    public ConsensusStatistics getConsensusStatistics() {
        return statistics;
    }

    public abstract int getConsensusCount();

    public abstract int getNumConsecutiveFailure();

    public abstract Object getState();

    @Override
    public boolean isStillRequiredToRun() {
        return getConsensusCount() < consensusLimit;
    }

    @Override
    public Pair<Double, List<Payload<T>>> processPayload(double time, Payload<T> payload) {
        statistics.addMessageCount(payload.getMessage().getType());
        return super.processPayload(time, payload);
    }

    /**
     * Tracks consensus related statistics.
     */
    @Override
    public void registerTimeElapsed(double time) {
        statistics.addTime(getState(), time);
        statistics.addRoundTime((getNumConsecutiveFailure() + 1), getState(), time);
        statistics.setConsensusCount(getConsensusCount());
    }
}
